### ISSUE TITLE
Drag, drop event need.

### ISSUE THREAD

**Issue by aasongWang** [wbhob/ionic-long-press#1]
Your plugin is very good.
But when I drag the button, release event is not work.
I need drag and drop event to solve this problem.
Please help me.

**Comment by wbhob** [comment]
I don't have time to create this feature right now, but I am open to and would appreciate pull requests for this feature.

**Comment by aasongWang** [comment]
I am a beginner.
Would you like to give me direction and reference, please?
I will make it.
Thanks.

**Comment by wbhob** [comment]
I'm not sure where I'd start with that. Check out HammerJS would be my recommendation. Thanks for your contribution!

**Comment by wbhob** [comment]
@aasongWang this tutorial may help you https://devdactic.com/ionic-2-drag-and-drop/
