### ISSUE TITLE
(onPressEnd) fires multiple event listener

### ISSUE THREAD

**Issue by ghost** [wbhob/ionic-long-press#11]
Hello,

i implemented the long press plugin in my project. But it works not as I want: the openRoom() is called 3-4 times by pressing on the rectangle.

`cli packages: (C:\Users\slippke\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 6.2.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

`        <g id="Rectangle_89" transform="translate(8 11)">
                <path class="st4" id="path89" d="M5,0h80l0,0v95l0,0H0l0,0V5C0,2.2,2.2,0,5,0z" ion-long-press [interval]="400" (onPressEnd)="openRoom(4)"
                />
                <text x="7" y="35 " letter-spacing="-0.5" font-size="10 ">{{temperatures[4]}} °C</text>
                <text x="7 " y="50 " letter-spacing="-0.5" font-size="10 "> {{humidities[4]}} %</text>
                <path class="st3" d="M5,1h78c0.6,0,1,0.4,1,1v91c0,0.6-0.4,1-1,1H1V5C1,2.8,2.8,1,5,1z" />
              </g>`
I combined the ion-long-press with an Angular Renderer 2:
`
        if (svgGroup) {
          this.render.listen(svgGroup, 'click', () => {
            console.log('You click on room: ' + room.roomID);
            this.roomToReseve = room.roomID;
            this.reserveRoom();
          });
        } else {
          console.log(this.selectorRectangle + ' has no event listner');
        }`

The Click should reserve the room / the press should open the room page.

Is this possible?

**Comment by wbhob** [comment]
Can you share a repo with this issue? Also, does it appear when you test on device?

**Comment by Jbz797** [comment]
Some news about this issue ?

I have the same with this code :

`      <ion-slide *ngFor="let photo of photos">
        <div ion-long-press (onPressEnd)="photoPressed(photo)" class="image" [ngStyle]="{'background-image':'linear-gradient(
          -180deg, transparent 80%, rgba(40, 40, 40, 0.8) 100%), url(' + (photo.localUrl || photo.downloadUrl) + ')'}"></div>
      </ion-slide>`

**Comment by wbhob** [comment]
I can't guarantee it works on dynamic elements like svg tags and slides, since those are more javascript-heavy. Do you run into this issue when you use a standard button?

**Comment by Jbz797** [comment]
When i use a button, my function is called 2 times when i press.

**Comment by ghost** [comment]
My standard solution of Angular is the best: (press)="functionToOpen()" works fine.

I should think simple.

**Comment by Jbz797** [comment]
Yes but (press) is equivalent to (onPressing). There is no equivalent to (onPressEnd) on the natives components.

**Comment by ghost** [comment]
But it doesn't work?? I tested (onPressing) in other **not**-svg combinations and it works.

**Comment by wbhob** [comment]
Yes, because it's *not standard* to put event listeners on SVG tags. Put the SVG in a button, and apply it to a button. As I said in my previous comment, I *can not guarantee* that this module will work on non-standard components. 

If you put this on a surrounding button and this issue persists, please open a new issue. For now, though, this is not a bug. This is outside of the scope of this package and an error due to not using the module as intended.
