### ISSUE TITLE
Can't bind to 'interval' since it isn't a known property of 'button'.

### ISSUE THREAD

**Issue by shri1983** [wbhob/ionic-long-press#12]
Hi,
Thanks in advanced. I am using your plugin but it is showing following error:

Can't bind to 'interval' since it isn't a known property of 'button'.

  <button ion-button ion-long-press [ERROR ->][interval]="400" (onPressStart)="pressed()" (onPressing)="active()" (onPressEnd)="released()">
</button"): 

And here is my development environments info:

ionic/app-scripts : 3.1.8
Cordova Platforms  : android 7.1.0
Ionic Framework    : ionic-angular 3.9.2
cordova (Cordova CLI) : 8.0.0
ionic/cli-utils        : 1.19.2
ionic (Ionic CLI)       : 3.20.0

**Comment by wbhob** [comment]
Have you imported the module into the PageModule of that page?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shri1983** [comment]
yes and its working fine now. I think it was a cache issue of ionic. I just restarted and relaunch the app and its working fine. Thanks for your support.
