### ISSUE TITLE
Does not work with user-select

### ISSUE THREAD

**Issue by chiemekailo** [wbhob/ionic-long-press#14]
whenever i apply the directive "ionic-long-press" to an html element in my ionic 3 project, all of the following css user-select styles stop working:
```
    -webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    user-select: text;
```
Texts no longer highlight and the options "copy", "lookup", and "share" do not show any longer.

**Comment by wbhob** [comment]
What platform, Ionic, and version are you on?

**Comment by chiemekailo** [comment]
I am on ionic 3.
I think they conflict because they both rely on the long-press event. I thought of trying to re-emit the event after the ionic-long-press callback function is called (_after un-binding the callback_), but thought it a little messy.
Instead, I bound to the **selectionchange** as well as the **touchend** events to get around the problem (_grabbing only the first of the multiple instances of selectionchange_) and using it with the touchend to call the intended callback function.
The ionic-long-press would have been way cooler though. Thanks.

**Comment by wbhob** [comment]
Sounds like you got it! Sorry I couldn't be of more help. Good luck with your app!
