### ISSUE TITLE
Error: bind to 'interval' since it isn't a known property of 'ion-card'.

### ISSUE THREAD

**Issue by devartstudio** [wbhob/ionic-long-press#3]
Hi, thank's for your plugin, 
2 months ago it's works very well, now i get this error:

Error: Uncaught (in promise): Error: Template parse errors: Can't bind to 'interval' since it isn't a known property of 'ion-card'. 1. If 'ion-card' is an Angular component and it has 'interval' input, then verify that it is part of this module. 2. If 'ion-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" text-center ion-long-press [ERROR ->][interval]="500" (onPressStart)="pressed()" (onPressing)="active()" (onPressEnd"): ...

my ionic info:

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 7.1.0 

local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:
    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.2.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro

best regards!
Ale

**Comment by wbhob** [comment]
Did you import the LongPressModule to your pages module?

**Comment by devartstudio** [comment]
Do you mean in my-page.module.ts ?

I just did In my-page.ts
import { LongPressModule } from 'ionic-long-press';

and in app.module.ts
import { LongPressModule } from 'ionic-long-press';
@NgModule({
...
imports: [
...
LongPressModule,
...]})

**Comment by devartstudio** [comment]
oh yeah!
I need to do in my-page.module.ts!
thank you so much!
