### ISSUE TITLE
Card List not scrolling after adding ion-long-press

### ISSUE THREAD

**Issue by evandrosimenes** [wbhob/ionic-long-press#30]
Hi all

im trying to add long press to an ionic card list e it works well...but it seems to get some conflict with the list scrolling....it just dont allow me to scroll the list anymore after adding long press.

any tip to make it works?

tks by your code.

**Comment by robbymichael1** [comment]
@evandrosimenes do you solve this?

**Comment by evandrosimenes** [comment]
> @evandrosimenes do you solve this?

@robbymichael1 i solved that by migrating for hammerjs.

**Comment by marcelonnunes** [comment]
@evandrosimenes , Could you provide sample code or indicate a tutorial on how to implement hammer.js? Thank you.

Obs: I realized that the list scrolling works as long as you select an element of the screen where you haven't applied the 'ion-long-press' event. But as there is little space on the screen for this, it is not viable.

**Comment by marcelonnunes** [comment]
> @evandrosimenes , Could you provide sample code or indicate a tutorial on how to implement hammer.js? Thank you.
> 
> Obs: I realized that the list scrolling works as long as you select an element of the screen where you haven't applied the 'ion-long-press' event. But as there is little space on the screen for this, it is not viable.

I found the solution. Just set the 'touch-action: pan-y' attribute in your css. It worked well for me.
```
ion-grid {  //Html element that has defined the 'ion-long-press' attribute
  display: block;  // I needed this to make my element touchable
  touch-action: pan-y !important;
}
```

Ref: -> https://github.com/hammerjs/hammer.js/issues/1014

**Comment by ghost** [comment]
`export class HammerConfig extends HammerGestureConfig {
  overrides = <any>{
    swipe: { direction: Hammer.DIRECTION_ALL }
  };
}`
and add to your scss 
`touch-action: pan-y !important;`
