### ISSUE TITLE
Not for press and hold events?

### ISSUE THREAD

**Issue by 1pocketaces1** [wbhob/ionic-long-press#5]
I have a press and hold feature in my ionic app where a meter fills as a buttom is held. I implemented ionic-long-press, but I don't want any function to fire on interval, I just want one function to fire on onPressStart and another on onPressEnd. When I test this in the browser device view, it starts just fine but then registers my click as a right click in my browser, not continuing the hold in the app.

I am wondering if it is related to the onPressing function of the plugin. I have not set it or an interval on my button, but it seems that the unwanted right-click register happens about half a second after the hold, and I know your default interval is 500ms.

Do you know how I might fix this? Thanks!
Here is my html button:

`<button ion-button ion-long-press
                (onPressStart)="startMeter()"
                (onPressEnd)="stopMeter()"
                id="meterBtn"
                style="height:100%">
        </button>`

**Comment by wbhob** [comment]
This may be more what you're looking for: https://www.develodesign.co.uk/news/angular/using-mouse-events-in-angular-4-5/
