### ISSUE TITLE
(onPressEnd) event method automatically call when view select on slide menu option.

### ISSUE THREAD

**Issue by LokeshPatel** [wbhob/ionic-long-press#7]
Hi,
I've used plugin  work fine on press button OnPress and OnPressEnd event but when view load from slide menu options Like (Home Page) then  OnPressEnd method call automatically after view load.

Please give me current solution for handle this case.
 
Also have one more issue : Many case OnPressEnd events not fire and onPressing continue run. suggest me how to close onPressing event if OnPressEnd method not fire.

Thanks

**Comment by jcphlux** [comment]
@LokeshPatel can you give more details on the first question.
On your second question are you using the NPM package or the code from the repo?

**Comment by LokeshPatel** [comment]
Hi,
Sorry for delay response.
I've uploaded sample code and video as well with lasted plugin NPM package.

Sample code : https://www.dropbox.com/s/y32uya5glc2txs7/democode.zip?dl=0
Demo Video : https://www.dropbox.com/s/72czixocy3lcrml/demovideo.mov?dl=0

Please check and verify, Also suggest me how to stop when Pressing event continues fire.

Thanks
Lokesh

**Comment by LokeshPatel** [comment]
Hi,
Any update for me?
Thanks

**Comment by wbhob** [comment]
i published 1.3.0. give that a try.
