### ISSUE TITLE
When button press on long time onPressEnd automatically fire without release of button.

### ISSUE THREAD

**Issue by LokeshPatel** [wbhob/ionic-long-press#8]
Hi,
I've long press button after some time onPressEnd event automatically fire without release button. 
This issue facing on android device. Could you please help to solve this issue.
I've used latest plugin code.

Thanks,
Lokesh

**Comment by wbhob** [comment]
You'll need to share some code please, I don't understand the problem.

**Comment by wbhob** [comment]
Closing due to lack of response. If this issue persists, please open a new issue with more details, like code and a screen recording.
